fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [--style=Google, -i]
      - id: clang-tidy
      #- id: cppcheck 
      #  args: [--language=c++, --suppress=missingInclude, --suppress=unusedFunction, --suppress=unmatchedSuppression]
      #- id: cpplint
